name: Build, Lint, Test

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  pull_request:
  push:
    branches: [main]

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  all:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: node_modules
          key: src-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install node_modules
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer--offline
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
