name: Deploy to GitHub Pages

defaults:
  run:
    shell: bash
    working-directory: ./site

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: node_modules
          key: src-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
