name: Deploy to GitHub Pages

defaults:
  run:
    shell: bash
    working-directory: ./site

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: node_modules
          key: site-${{ runner.os }}-${{ hashFiles('./site/yarn.lock') }}
      - name: Install node_modules
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer--offline
      - name: Build Website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
